import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { NavMenu } from "./_component/navMenu";
import ForHead from "./_component/forHead";
import ForFooter from "./_component/forFooter";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>){
  
  return (
    
    <ClerkProvider>
       <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
          <header>
              <h2>Weather-Saver</h2>
              <ForHead/>
          </header>

          <section className="sidebar">

              <nav>
                <NavMenu/>
              </nav>
              
              <article>
                  {children}
              </article>

          </section>

          <footer>
              <p>&copy;All Copy Rights Reserved ❤️ Developed by Ashutosh Kumar</p>
              <ForFooter/>
          </footer>

      </body>
    </html>
   </ClerkProvider>
  );
}
